# Generated by Django 5.0 on 2023-12-23 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedrooms', models.IntegerField()),
                ('number_of_people', models.IntegerField()),
                ('has_ac', models.BooleanField()),
                ('has_tv', models.BooleanField()),
                ('number_of_fans', models.IntegerField()),
                ('uses_energy_efficient_appliances', models.BooleanField()),
                ('uses_renewable_energy', models.BooleanField()),
                ('washing_machine_usage', models.CharField(max_length=100)),
                ('number_of_electronic_devices', models.CharField(max_length=100)),
                ('electricity_bill', models.FloatField()),
                ('prediction_result', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
