# Generated by Django 5.0 on 2023-12-24 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserPrediction',
            new_name='BillPred',
        ),
    ]
