# Generated by Django 5.0 on 2023-12-24 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_userprediction_billpred'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billpred',
            name='electricity_bill',
        ),
    ]
